In [1]:
import pandas as pd
import numpy as np
import cv2
import os
import torch
import json

In [2]:
os.listdir("../input/floor_plan")

['test_images',
 'sample_submit.json',
 'train_annotations',
 '.DS_Store',
 'evaluation_code',
 'readme.md',
 'train_images']

In [20]:
path = "../input/floor_plan/train_annotations/train_0000.json"
with open(path) as f:
    data = json.load(f)
for label in data["labels"]:
    print(label)
    for item in data["labels"][label]:
        pts = np.array(item)
        #print(pts)
        print(pts[:,0],pts[:,1])

LDK
[[473.8089172   81.43949045]
 [278.9044586   80.80254777]
 [280.81528662 278.89171975]
 [183.36305732 278.25477707]
 [181.4522293  323.47770701]
 [278.26751592 327.29936306]
 [278.9044586  520.29299363]
 [475.08280255 519.01910828]]
[473.8089172  278.9044586  280.81528662 183.36305732 181.4522293
 278.26751592 278.9044586  475.08280255] [ 81.43949045  80.80254777 278.89171975 278.25477707 323.47770701
 327.29936306 520.29299363 519.01910828]
浴室
[[ 33.68152866  83.35031847]
 [133.04458599  83.35031847]
 [133.68152866 180.80254777]
 [ 36.86624204 182.07643312]]
[ 33.68152866 133.04458599 133.68152866  36.86624204] [ 83.35031847  83.35031847 180.80254777 182.07643312]
廊下
[[ 60.43312102 230.48407643]
 [ 62.98089172 278.25477707]
 [133.04458599 302.45859873]
 [131.77070064 326.02547771]
 [183.36305732 327.29936306]
 [184.63694268 180.80254777]
 [134.95541401 179.52866242]
 [134.31847134 228.57324841]]
[ 60.43312102  62.98089172 133.04458599 131.77070064 183.36305732
 184.63694268 134.95

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed